#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Commands
fpath=(/usr/local/share/zsh-completions $fpath) # zsh-completions

# kubectl completions
source <(kubectl completion zsh)

# Aliases

# System commands
alias ll='ls -la'

# Navigation
alias dev='cd ~/Developer'
alias preztoconf='cd ~/.zprezto'

# git
alias gdel='git branch --merged | grep -v "\master" | xargs -n 1 git branch -d'
alias gpc='git push --set-upstream origin "$(git-branch-current 2> /dev/null)"'
alias gpp='git pull origin "$(git-branch-current 2> /dev/null)" && git push origin "$(git-branch-current 2> /dev/null)"'
alias gpho='git push origin "$(git-branch-current 2> /dev/null)"'
alias gplo='git pull origin "$(git-branch-current 2> /dev/null)"'
alias gst='git status'
alias gal='git add .'
alias gcd='git checkout develop'
alias gcdot='git checkout -- .'
alias gmit='git commit'

# java
jdk() {
  version=$1
  export JAVA_HOME=$(/usr/libexec/java_home -v"$version")
  java -version
}

# default to Java 17
jdk 17

# Golang private repo access
go env -w GOPRIVATE='github.com/inloco/*'

# other commands
alias interfaces='go get -u github.com/inloco/interfaces/go'

# SSO
alias gbenv='source ~/Developer/aws-entrypoint/global'

# default to production
export AWS_PROFILE=incognia-production-product

alias stagingProfile='export AWS_PROFILE=incognia-staging-product'
alias productionProfile='export AWS_PROFILE=incognia-production-product'

# Python
alias python='python3'
alias bpy='/opt/homebrew/bin/python3'

# Xcode
alias xcodeselect16='sudo xcode-select -s /Applications/Xcode16.app'
alias xcodeselect='sudo xcode-select -s /Applications/Xcode.app'

# apk <package_name>
apk() {	
	local APK3=$(adb shell pm path $1) &&
                adb pull ${APK3#*:} ~/Downloads/ ;
	            open ~/Downloads/ ;
		        open ~/Downloads/base.apk 
}

# GPG Signing
export GPG_TTY=$TTY

# React Native environment
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

export LANG=en_US.UTF-8