#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Commands
fpath=(/usr/local/share/zsh-completions $fpath) # zsh-completions

# Aliases

# System commands
alias ll='ls -la'

# Navigation
alias dev='cd ~/Developer'
alias preztoconf='cd ~/.zprezto'

# git
alias gdel='git branch --merged | grep -v "\master" | xargs -n 1 git branch -d'
alias gpc='git push --set-upstream origin "$(git-branch-current 2> /dev/null)"'
alias gpp='git pull origin "$(git-branch-current 2> /dev/null)" && git push origin "$(git-branch-current 2> /dev/null)"'
alias gpho='git push origin "$(git-branch-current 2> /dev/null)"'
alias gplo='git pull origin "$(git-branch-current 2> /dev/null)"'
alias gst='git status'
alias gal='git add .'
alias gcd='git checkout develop'
alias gcdot='git checkout -- .'
alias gmit='git commit'

# java
alias java8='export JAVA_HOME=$JAVA_8_HOME'
alias java11='export JAVA_HOME=$JAVA_11_HOME'
alias java15='export JAVA_HOME=$JAVA_15_HOME'

# default to Java 8
java8

# other commands
alias historian='docker -- run -p 9999:9999 gcr.io/android-battery-historian/stable:3.1 --port 9999'

# SSO
alias brenv='source ~/Developer/aws-entrypoint/br'
alias gbenv='source ~/Developer/aws-entrypoint/global' 

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/larissa.navarro/.sdkman"
[[ -s "/Users/larissa.navarro/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/larissa.navarro/.sdkman/bin/sdkman-init.sh"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
